import '../models/project_model.dart';
import '../models/user_model.dart';
import '../models/message_model.dart';

// Datos de demo para mostrar la app sin backend
class DemoData {
  // Usuario demo inversor
  static final UserModel demoInvestor = UserModel(
    id: 'investor_001',
    email: 'juan@inversiones.ar',
    fullName: 'Juan Martínez',
    avatarUrl: null,
    role: UserRole.investor,
    kycStatus: KycStatus.verified,
    plan: SubscriptionPlan.pro,
    province: 'Buenos Aires (CABA)',
    bio: 'Angel investor con foco en Fintech y Agtech. +10 años de experiencia en el ecosistema emprendedor argentino.',
    linkedinUrl: 'https://linkedin.com/in/juanmartinez',
    isActive: true,
    createdAt: DateTime(2024, 1, 15),
    investorProfile: InvestorProfile(
      userId: 'investor_001',
      preferredVerticals: ['Fintech', 'Agtech', 'SaaS'],
      preferredStages: ['Pre-seed', 'Seed'],
      preferredTicketRange: 'USD 50k – 200k',
      preferredProvinces: ['Buenos Aires (CABA)', 'Córdoba'],
      impactFocus: ['Inclusión financiera', 'Impacto social'],
      isAngelInvestor: true,
      totalInvestments: 7,
      portfolioSize: 850000,
    ),
  );

  // Usuario demo emprendedor
  static final UserModel demoFounder = UserModel(
    id: 'founder_001',
    email: 'maria@agrotech.ar',
    fullName: 'María González',
    avatarUrl: null,
    role: UserRole.founder,
    kycStatus: KycStatus.verified,
    plan: SubscriptionPlan.pro,
    province: 'Córdoba',
    bio: 'CEO & Co-founder de AgroSense. Ingeniera agrónoma con MBA. Apasionada por la tecnología al servicio del campo argentino.',
    linkedinUrl: 'https://linkedin.com/in/mariagonzalez',
    isActive: true,
    createdAt: DateTime(2024, 3, 10),
    founderProfile: FounderProfile(
      userId: 'founder_001',
      companyName: 'AgroSense',
      vertical: 'Agtech',
      stage: 'Seed',
      ticketSeeking: 'USD 200k – 1M',
      province: 'Córdoba',
      impactFocus: ['Impacto ambiental', 'Sostenibilidad'],
      websiteUrl: 'https://agrosense.ar',
      mrr: 18000,
      teamSize: 8,
      foundedYear: 2022,
    ),
  );

  // Proyectos demo
  static final List<ProjectModel> projects = [
    ProjectModel(
      id: 'proj_001',
      founderId: 'founder_001',
      founderName: 'María González',
      title: 'AgroSense',
      description: 'Plataforma IoT para monitoreo inteligente de cultivos. Sensores en campo + IA predictiva para optimizar el rendimiento agrícola y reducir el uso de agua hasta un 40%.',
      vertical: 'Agtech',
      stage: 'Seed',
      ticketSeeking: 'USD 200k – 1M',
      province: 'Córdoba',
      impactFocus: ['Impacto ambiental', 'Sostenibilidad'],
      imageUrls: [],
      isHighlighted: true,
      isActive: true,
      metrics: ProjectMetrics(
        totalViews: 342,
        uniqueViews: 189,
        contactsReceived: 14,
        savedAsFavorite: 28,
        pitchOpens: 97,
        pitchCtr: 28.4,
        meetingsScheduled: 5,
      ),
      createdAt: DateTime(2024, 3, 10),
      updatedAt: DateTime(2024, 6, 1),
      mrr: 18000,
      teamSize: 8,
      foundedYear: 2022,
      problemStatement: 'El 35% del agua de riego se desperdicia por falta de datos en tiempo real. Los productores toman decisiones a ciegas.',
      solutionStatement: 'Sensores IoT solares conectados a una app que muestra humedad del suelo, clima y recomendaciones de riego en tiempo real.',
      businessModel: 'SaaS mensual por hectárea monitorizada + venta de hardware de sensores.',
      competitiveAdvantage: 'Única solución diseñada para las condiciones del campo argentino. Batería solar que dura 5 años sin mantenimiento.',
      fundingRaised: 80000,
      websiteUrl: 'https://agrosense.ar',
    ),
    ProjectModel(
      id: 'proj_002',
      founderId: 'founder_002',
      founderName: 'Lucas Fernández',
      title: 'FincluyAR',
      description: 'Billetera digital y microcréditos para trabajadores informales. Usamos IA para scoring crediticio alternativo sin historial bancario tradicional.',
      vertical: 'Fintech',
      stage: 'Pre-seed',
      ticketSeeking: 'Hasta USD 10k',
      province: 'Buenos Aires (CABA)',
      impactFocus: ['Inclusión financiera', 'Impacto social'],
      imageUrls: [],
      isHighlighted: true,
      isActive: true,
      metrics: ProjectMetrics(
        totalViews: 521,
        uniqueViews: 310,
        contactsReceived: 22,
        savedAsFavorite: 45,
        pitchOpens: 188,
        pitchCtr: 36.1,
        meetingsScheduled: 9,
      ),
      createdAt: DateTime(2024, 2, 20),
      updatedAt: DateTime(2024, 5, 28),
      teamSize: 5,
      foundedYear: 2023,
      problemStatement: '12 millones de argentinos no tienen acceso a crédito formal por trabajar en la informalidad.',
      solutionStatement: 'Scoring alternativo basado en comportamiento de pagos de servicios, movilidad y patrones de consumo.',
      businessModel: 'Spread en microcréditos + fee por transacción en billetera.',
    ),
    ProjectModel(
      id: 'proj_003',
      founderId: 'founder_003',
      founderName: 'Sofía Rodríguez',
      title: 'EduPlay',
      description: 'Plataforma de aprendizaje gamificado para niños de 5 a 12 años. Contenido curricular oficial en formato de juegos adaptivos con IA.',
      vertical: 'Edtech',
      stage: 'Seed',
      ticketSeeking: 'USD 50k – 200k',
      province: 'Buenos Aires (GBA)',
      impactFocus: ['Educación', 'Impacto social'],
      imageUrls: [],
      isHighlighted: false,
      isActive: true,
      metrics: ProjectMetrics(
        totalViews: 198,
        uniqueViews: 134,
        contactsReceived: 8,
        savedAsFavorite: 19,
        pitchOpens: 62,
        pitchCtr: 31.3,
        meetingsScheduled: 3,
      ),
      createdAt: DateTime(2024, 4, 5),
      updatedAt: DateTime(2024, 6, 10),
      mrr: 5500,
      teamSize: 4,
      foundedYear: 2023,
      problemStatement: 'Los chicos no quieren estudiar con libros digitales aburridos. La brecha de aprendizaje post-pandemia es enorme.',
      solutionStatement: 'Juegos que se adaptan al nivel de cada niño. Si va bien, sube dificultad. Si va mal, refuerza el concepto de otra forma.',
      businessModel: 'Suscripción familiar mensual + licencias para colegios.',
    ),
    ProjectModel(
      id: 'proj_004',
      founderId: 'founder_004',
      founderName: 'Martín López',
      title: 'MediAlert',
      description: 'Sistema de alertas inteligentes para pacientes crónicos. Recordatorios de medicación + telemedicina + conexión con médicos de cabecera.',
      vertical: 'Healthtech',
      stage: 'Pre-seed',
      ticketSeeking: 'USD 10k – 50k',
      province: 'Mendoza',
      impactFocus: ['Salud', 'Impacto social'],
      imageUrls: [],
      isHighlighted: false,
      isActive: true,
      metrics: ProjectMetrics(
        totalViews: 156,
        uniqueViews: 98,
        contactsReceived: 6,
        savedAsFavorite: 12,
        pitchOpens: 41,
        pitchCtr: 26.3,
        meetingsScheduled: 2,
      ),
      createdAt: DateTime(2024, 5, 1),
      updatedAt: DateTime(2024, 6, 5),
      teamSize: 3,
      foundedYear: 2024,
      problemStatement: 'El 40% de los pacientes crónicos no toma su medicación correctamente. Esto genera reinternaciones evitables.',
      solutionStatement: 'App con recordatorios personalizados, control familiar remoto y alertas al médico si hay incumplimiento reiterado.',
      businessModel: 'B2B con obras sociales y prepagas. Fee por paciente activo.',
    ),
    ProjectModel(
      id: 'proj_005',
      founderId: 'founder_005',
      founderName: 'Carolina Pérez',
      title: 'PropTech360',
      description: 'Marketplace inmobiliario con recorridos virtuales 360° y firma digital de contratos. Eliminamos los intermediarios innecesarios.',
      vertical: 'Proptech',
      stage: 'Serie A',
      ticketSeeking: 'USD 200k – 1M',
      province: 'Buenos Aires (CABA)',
      impactFocus: ['Sin foco de impacto'],
      imageUrls: [],
      isHighlighted: true,
      isActive: true,
      metrics: ProjectMetrics(
        totalViews: 789,
        uniqueViews: 445,
        contactsReceived: 31,
        savedAsFavorite: 67,
        pitchOpens: 234,
        pitchCtr: 29.7,
        meetingsScheduled: 12,
      ),
      createdAt: DateTime(2023, 11, 15),
      updatedAt: DateTime(2024, 6, 12),
      mrr: 95000,
      arr: 1140000,
      teamSize: 22,
      foundedYear: 2021,
      fundingRaised: 350000,
      problemStatement: 'Alquilar o comprar una propiedad tarda meses por burocracia y falta de digitalización.',
      solutionStatement: 'Tour virtual 360° desde el celular + contratos digitales con firma electrónica. Cerrar un contrato en 48 horas.',
      businessModel: 'Comisión del 2% sobre transacciones + suscripción para inmobiliarias.',
    ),
    ProjectModel(
      id: 'proj_006',
      founderId: 'founder_006',
      founderName: 'Diego Sánchez',
      title: 'LogiMove',
      description: 'Última milla inteligente para PyMEs. Optimización de rutas + tracking en tiempo real + red de operadores logísticos independientes.',
      vertical: 'Logística',
      stage: 'Seed',
      ticketSeeking: 'USD 50k – 200k',
      province: 'Buenos Aires (GBA)',
      impactFocus: ['Empleo', 'Impacto social'],
      imageUrls: [],
      isHighlighted: false,
      isActive: true,
      metrics: ProjectMetrics(
        totalViews: 267,
        uniqueViews: 178,
        contactsReceived: 11,
        savedAsFavorite: 23,
        pitchOpens: 89,
        pitchCtr: 33.3,
        meetingsScheduled: 4,
      ),
      createdAt: DateTime(2024, 1, 20),
      updatedAt: DateTime(2024, 6, 8),
      mrr: 32000,
      teamSize: 12,
      foundedYear: 2022,
      problemStatement: 'Las PyMEs pagan hasta 3 veces más por logística que las grandes empresas por no tener poder de negociación.',
      solutionStatement: 'Pool de demanda + red de repartidores independientes + algoritmo de optimización de rutas en tiempo real.',
      businessModel: 'Fee del 8% por envío + suscripción para clientes recurrentes.',
    ),
  ];

  // Pipeline demo para inversores
  static final List<PipelineEntry> pipeline = [
    PipelineEntry(
      id: 'pipe_001',
      investorId: 'investor_001',
      projectId: 'proj_001',
      project: projects[0],
      stage: PipelineStage.dueDiligence,
      notes: 'Muy sólido. Reunión con María el 15/6. Pedir estados financieros auditados.',
      addedAt: DateTime(2024, 4, 10),
      updatedAt: DateTime(2024, 6, 10),
    ),
    PipelineEntry(
      id: 'pipe_002',
      investorId: 'investor_001',
      projectId: 'proj_002',
      project: projects[1],
      stage: PipelineStage.met,
      notes: 'Pitch excelente. Equipo técnico muy fuerte. Validar métricas de morosidad.',
      addedAt: DateTime(2024, 5, 2),
      updatedAt: DateTime(2024, 6, 5),
    ),
    PipelineEntry(
      id: 'pipe_003',
      investorId: 'investor_001',
      projectId: 'proj_005',
      project: projects[4],
      stage: PipelineStage.evaluating,
      notes: 'MRR sólido. Analizar competencia con ZonaProp y Argenprop.',
      addedAt: DateTime(2024, 5, 20),
      updatedAt: DateTime(2024, 5, 25),
    ),
    PipelineEntry(
      id: 'pipe_004',
      investorId: 'investor_001',
      projectId: 'proj_003',
      project: projects[2],
      stage: PipelineStage.contacted,
      notes: null,
      addedAt: DateTime(2024, 6, 1),
      updatedAt: DateTime(2024, 6, 1),
    ),
    PipelineEntry(
      id: 'pipe_005',
      investorId: 'investor_001',
      projectId: 'proj_004',
      project: projects[3],
      stage: PipelineStage.discovered,
      notes: null,
      addedAt: DateTime(2024, 6, 12),
      updatedAt: DateTime(2024, 6, 12),
    ),
  ];

  // Conversaciones demo
  static final List<ConversationModel> conversations = [
    ConversationModel(
      id: 'conv_001',
      projectId: 'proj_001',
      projectTitle: 'AgroSense',
      investorId: 'investor_001',
      investorName: 'Juan Martínez',
      founderId: 'founder_001',
      founderName: 'María González',
      lastMessage: MessageModel(
        id: 'msg_010',
        conversationId: 'conv_001',
        senderId: 'founder_001',
        senderName: 'María González',
        content: 'Perfecto Juan! Te mando el deck actualizado con las proyecciones a 3 años.',
        type: MessageType.text,
        status: MessageStatus.read,
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      ),
      unreadCount: 0,
      updatedAt: DateTime.now().subtract(const Duration(hours: 2)),
    ),
    ConversationModel(
      id: 'conv_002',
      projectId: 'proj_002',
      projectTitle: 'FincluyAR',
      investorId: 'investor_001',
      investorName: 'Juan Martínez',
      founderId: 'founder_002',
      founderName: 'Lucas Fernández',
      lastMessage: MessageModel(
        id: 'msg_020',
        conversationId: 'conv_002',
        senderId: 'founder_002',
        senderName: 'Lucas Fernández',
        content: 'Hola Juan! Gracias por tu interés. ¿Cuándo podemos hacer una intro call?',
        type: MessageType.text,
        status: MessageStatus.delivered,
        createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      ),
      unreadCount: 2,
      updatedAt: DateTime.now().subtract(const Duration(hours: 5)),
    ),
    ConversationModel(
      id: 'conv_003',
      projectId: 'proj_005',
      projectTitle: 'PropTech360',
      investorId: 'investor_001',
      investorName: 'Juan Martínez',
      founderId: 'founder_005',
      founderName: 'Carolina Pérez',
      lastMessage: MessageModel(
        id: 'msg_030',
        conversationId: 'conv_003',
        senderId: 'investor_001',
        senderName: 'Juan Martínez',
        content: 'Excelente reunión Carolina. Voy a revisar los números con mi equipo.',
        type: MessageType.text,
        status: MessageStatus.read,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
      ),
      unreadCount: 0,
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
  ];

  // Mensajes demo de una conversación
  static List<MessageModel> getMessages(String conversationId) {
    if (conversationId == 'conv_001') {
      return [
        MessageModel(
          id: 'msg_001',
          conversationId: 'conv_001',
          senderId: 'investor_001',
          senderName: 'Juan Martínez',
          content: 'Hola María! Vi tu proyecto AgroSense y me pareció muy interesante. ¿Tenés 30 minutos para una intro call?',
          type: MessageType.text,
          status: MessageStatus.read,
          createdAt: DateTime.now().subtract(const Duration(days: 3, hours: 4)),
        ),
        MessageModel(
          id: 'msg_002',
          conversationId: 'conv_001',
          senderId: 'founder_001',
          senderName: 'María González',
          content: '¡Hola Juan! Claro que sí, con mucho gusto. ¿Qué día te queda bien?',
          type: MessageType.text,
          status: MessageStatus.read,
          createdAt: DateTime.now().subtract(const Duration(days: 3, hours: 3)),
        ),
        MessageModel(
          id: 'msg_003',
          conversationId: 'conv_001',
          senderId: 'investor_001',
          senderName: 'Juan Martínez',
          content: '¿El jueves a las 15hs?',
          type: MessageType.text,
          status: MessageStatus.read,
          createdAt: DateTime.now().subtract(const Duration(days: 3, hours: 2)),
        ),
        MessageModel(
          id: 'msg_004',
          conversationId: 'conv_001',
          senderId: 'founder_001',
          senderName: 'María González',
          content: 'Perfecto! Agendado. Te mando el link de Zoom.',
          type: MessageType.text,
          status: MessageStatus.read,
          createdAt: DateTime.now().subtract(const Duration(days: 3, hours: 1)),
        ),
        MessageModel(
          id: 'msg_005',
          conversationId: 'conv_001',
          senderId: 'investor_001',
          senderName: 'Juan Martínez',
          content: 'Excelente charla María! El producto me parece muy sólido. Me gustaría ver el pitch deck completo y los estados financieros.',
          type: MessageType.text,
          status: MessageStatus.read,
          createdAt: DateTime.now().subtract(const Duration(hours: 26)),
        ),
        MessageModel(
          id: 'msg_006',
          conversationId: 'conv_001',
          senderId: 'founder_001',
          senderName: 'María González',
          content: 'Perfecto Juan! Te mando el deck actualizado con las proyecciones a 3 años.',
          type: MessageType.text,
          status: MessageStatus.read,
          createdAt: DateTime.now().subtract(const Duration(hours: 2)),
        ),
      ];
    }
    return [];
  }

  // Reuniones demo
  static final List<MeetingModel> meetings = [
    MeetingModel(
      id: 'meet_001',
      conversationId: 'conv_001',
      requesterId: 'investor_001',
      requesterName: 'Juan Martínez',
      receiverId: 'founder_001',
      receiverName: 'María González',
      projectId: 'proj_001',
      projectTitle: 'AgroSense',
      scheduledAt: DateTime.now().add(const Duration(days: 2, hours: 3)),
      durationMinutes: 30,
      status: MeetingStatus.confirmed,
      meetingUrl: 'https://zoom.us/j/123456789',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    MeetingModel(
      id: 'meet_002',
      conversationId: 'conv_002',
      requesterId: 'founder_002',
      requesterName: 'Lucas Fernández',
      receiverId: 'investor_001',
      receiverName: 'Juan Martínez',
      projectId: 'proj_002',
      projectTitle: 'FincluyAR',
      scheduledAt: DateTime.now().add(const Duration(days: 5)),
      durationMinutes: 45,
      status: MeetingStatus.pending,
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
    ),
  ];

  // Analytics demo
  static Map<String, dynamic> getAnalytics(String projectId) {
    return {
      'metrics': {
        'totalViews': 342,
        'uniqueViews': 189,
        'contactsReceived': 14,
        'savedAsFavorite': 28,
        'pitchOpens': 97,
        'pitchCtr': 28.4,
        'meetingsScheduled': 5,
      },
      'weeklyViews': [23.0, 41.0, 38.0, 55.0, 62.0, 48.0, 75.0],
    };
  }
}
